version: "3"
services:
  skoser:
    build: .
    command: python3 script.py
    volumes:
      - .:/code

  raptor:
    container_name: raptor
    image: pheyvaer/raptor
    depends_on: 
      - skoser
    restart: on-failure
    volumes:
      - .:/code
    entrypoint: ["/bin/bash", "/code/rapper.sh"]